### ISSUE TITLE
 Fetched in submodule path 'Sources/H5/EventTracing-web', but it did not contain 4a1c86165d1db0f183939fd34cf69635714b3cdc. Direct fetching of that commit failed.

### ISSUE THREAD

**Issue by iStig** [eventtracing/dawn#1]
是不是提交遗漏了

**Comment by ShakeShakeMe** [comment]
主工程 dawn 拿下来代码后，执行 `git submodule update --init --recursive` 来在当前工程下获取所有子模块。

目前是用默认分支来指定的子模块，我们后面修改为tag，这样就稳定了；
如果你使用上面的命令拿不代码，可以试试 `git submodule update --force --recursive --init --remote` 强制拉下来。

**Comment by iStig** [comment]
> 主工程 dawn 拿下来代码后，执行 `git submodule update --init --recursive` 来在当前工程下获取所有子模块。
> 
> 目前是用默认分支来指定的子模块，我们后面修改为tag，这样就稳定了； 如果你使用上面的命令拿不代码，可以试试 `git submodule update --force --recursive --init --remote` 强制拉下来。

按照你的方式也是拉不下来的

`
➜  dawn git:(master) ✗ git submodule update --force --recursive --init --remote
Cloning into '/Users/zhangjianming/Desktop/dawn/Sources/H5/EventTracing-web'...
ssh_dispatch_run_fatal: Connection to 20.205.243.166 port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:eventtracing/easyinsight-web.git' into submodule path '/Users/zhangjianming/Desktop/dawn/Sources/H5/EventTracing-web' failed
Failed to clone 'Sources/H5/EventTracing-web'. Retry scheduled
Cloning into '/Users/zhangjianming/Desktop/dawn/Sources/iOS/EventTracing-iOS-Debug'...
ssh_dispatch_run_fatal: Connection to 20.205.243.166 port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:eventtracing/EventTracing-iOS-Debug.git' into submodule path '/Users/zhangjianming/Desktop/dawn/Sources/iOS/EventTracing-iOS-Debug' failed
Failed to clone 'Sources/iOS/EventTracing-iOS-Debug'. Retry scheduled
Cloning into '/Users/zhangjianming/Desktop/dawn/Sources/iOS/EventTracing-iOS-LogViewer'...
kex_exchange_identification: Connection closed by remote host
Connection closed by 20.205.243.166 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:eventtracing/EventTracing-iOS-LogViewer.git' into submodule path '/Users/zhangjianming/Desktop/dawn/Sources/iOS/EventTracing-iOS-LogViewer' failed
Failed to clone 'Sources/iOS/EventTracing-iOS-LogViewer'. Retry scheduled
Cloning into '/Users/zhangjianming/Desktop/dawn/Sources/H5/EventTracing-web'...
kex_exchange_identification: Connection closed by remote host
Connection closed by 20.205.243.166 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:eventtracing/easyinsight-web.git' into submodule path '/Users/zhangjianming/Desktop/dawn/Sources/H5/EventTracing-web' failed
Failed to clone 'Sources/H5/EventTracing-web' a second time, aborting
`

**Comment by iStig** [comment]
@ShakeShakeMe
